# yaml-language-server: $schema=https://raw.githubusercontent.com/guettli/dotfiles/main/config.schema.json
name: Your Name
personal_email: you@example.com
orgs:
  - url: github.com/your-company
    email: you@your-company.com
